spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa

app:
  messages:
    contactSaveSucc: Contact Saved
    contactSaveFail: Failed to save contact
    contactDelSucc: Contact Deleted
    contactDelFail: Failed to Delete contact